
#setting up service name from serveless.com
service: helloworld
# app name from dashboard.serverless.com
app: my-aws-node-rest-api-app
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

# Add you aws region
  #stage: dev
  region: ap-south-1

functions:
  helloworld:
    handler: handler.helloworld
#    Code for create apis

    events:
      - httpApi:
          path: /v1/helloworld
          method: get